server:
  port: 8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false   
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true 
    hostname: localhost
    
logging:
  level:
    '[org.springframework.core.io.support]': DEBUG
    '[org.springframework.context.annotation]': DEBUG